using sly.lexer;

namespace JMC.Parser;
public enum TokenType
{
    #region Sugar
    [SingleLineComment("//")]
    Comment,
    [Sugar("++")]
    Increment,
    [Sugar("--")]
    Decrement,
    [Sugar("+")]
    Plus,
    [Sugar("-")]
    Minus,
    [Sugar("*")]
    Multiply,
    [Sugar("/")]
    Divide,
    [Sugar("%")]
    Remainder,
    [Sugar(">")]
    GreaterThan,
    [Sugar("<")]
    LessThan,
    [Sugar("==")]
    Equal,
    [Sugar("!=")]
    NotEqual,
    [Sugar(">=")]
    GreaterThanOrEqual,
    [Sugar("<=")]
    LessThanOrEqual,
    [Sugar("=")]
    Assign,
    [Sugar("%=")]
    RemainderAssign,
    [Sugar("+=")]
    PlusAssign,
    [Sugar("-=")]
    MinusAssign,
    [Sugar("*=")]
    MultiplyAssign,
    [Sugar("/=")]
    DivideAssign,
    [Sugar("><")]
    CompareAssign,
    [Sugar("??=")]
    NullColesleAssign,
    [Sugar("=>")]
    Arrow,
    [Sugar("{")]
    BlockStart,
    [Sugar("}")]
    BlockEnd,
    [Sugar("[")]
    ListStart,
    [Sugar("]")]
    ListEnd,
    [Sugar("(")]
    ParenStart,
    [Sugar(")")]
    PareenEnd,
    [Sugar(":")]
    Colon,
    [Sugar("::")]
    Imply,
    [Sugar("@[parse]")]
    Selector,
    [Sugar(",")]
    Separator,
    [Sugar(";")]
    End,
    [Sugar("!")]
    Not,
    [Sugar("$")]
    Variable,
    #endregion

    #region Keywords
    [Keyword("true")]
    True,
    [Keyword("false")]
    False,
    [Keyword("run")]
    RunKeyword,
    [Keyword("import")]
    ImportKeyword,
    [Keyword("function")]
    FunctionKeyword,
    [Keyword("while")]
    WhileKeyword,
    [Keyword("if")]
    IfKeyword,
    [Keyword("else")]
    ElseKeyword,
    [Keyword("do")]
    DoKeyword,
    [Keyword("class")]
    ClassKeyword,
    [Keyword("new")]
    NewKeyword,
    [Keyword("null")]
    NullKeyword,
    #endregion

    [Int]
    Int,
    [Double]
    Float,
    [String]
    [String("'")]
    String,
    [AlphaNumDashId]
    Identifier
}
